### PR TITLE
Exclude .terraform folder from user uploaded quoin tar archive

### LINKED ISSUE #43: Eve create infra fails for quoin tars containing terraform artifacts
If there is a `.terraform` folder in the cwd when creating a quoin, it will be uploaded in the tar file and cause the create infra command to fail. Not sure if this is something we should just remember to delete, or if the folder can be ignored when creating the quoin/infra.

### PR DESCRIPTION
**Pull request by weitenghuang**
**What this PR does**:

To avoid terraform state, or version conflict between eve and user's local terraform. We decide to NOT take in user's .terraform folder from tar archive

**Which issue this PR fixes**:
Fix #43

**Release note**:
- Add filter for  to skip `.terraform` folder from user's upload Quoin Archive
- Add exclusion in evectl shell script to ignore `.terraform` folder
- Change `writeFileFromTarGz` from struct member method to function with `io.reader`, `directory` inputs
- Using `io.reader` argument allows us to provide different readers (byte reader vs file reader)
- Test `writeFileFromTarGz` with File reader

### CODE REVIEW

**Comment by weitenghuang** [comment]
@dragan , yes, i need to add testing, and update the evectl shell script.

**Comment by weitenghuang** [comment]
@dragan and @nicklathe , can you help to review my PR? Thank you

File: pkg/terraform/terraform.go [hunk 1]
```diff
@@ -171,16 +172,16 @@ func setWorkDir(name string, retry int) (dir string) {
 	return dir
 }
 
-func (tf *Terraform) writeFileFromTarGz(perm os.FileMode) error {
-	r := bytes.NewReader(tf.modules)
+func writeFileFromTarGz(r io.Reader, dir string, perm os.FileMode) error {
+	// r := bytes.NewReader(tf.modules)
```
Comment (dragan) [inline pkg/terraform/terraform.go]: If we do not need this, go ahead and just remove it.
